# Generated by Django 6.0 on 2025-12-30 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('connections_sent', models.IntegerField(default=0)),
                ('connections_accepted', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('profiles_searched', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
            },
        ),
        migrations.AlterModelOptions(
            name='linkedinprofile',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='ConnectionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField()),
                ('profile_name', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['profile_url'], name='automation__profile_7cd4ef_idx'), models.Index(fields=['sent_at'], name='automation__sent_at_f6dd19_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_url', models.URLField()),
                ('recipient_name', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template_used', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_url'], name='automation__recipie_2a2794_idx'), models.Index(fields=['sent_at'], name='automation__sent_at_438902_idx')],
            },
        ),
    ]
