# Generated by Django 6.0 on 2025-12-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_dailystats_alter_linkedinprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelTable(
            name='linkedinprofile',
            table='linkedin_db_network_data',
        ),
    ]
